site_name: My R-Type
site_url: http://127.0.0.1:8000/
theme: windmill
nav:
  - Home: present.md
  - Tools Reference: toolreference.md
  - About: about.md
  - Index: index.md
  - Protocole RFC: rfcprotocole.md
  - ENet Server: serveur.md
  - ENet Client: client.md
